version: "2.23.3-desktop.2"

services:
  server:
    build: .
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      - redis

  redis:
    image: redis/redis-stack-server
    ports:
      - "6379:6379"
