const SOCKET_CONST = {
	MESSAGE_RECEIVED_FROM_CLIENT: "MESSAGE_SENT",
	NEW_MESSAGE: "NEW_MESSAGE",
	MESSAGE_SENT_FROM_SERVER: "MESSAGE_RECEIVED",
	OFFLINE: "OFFLINE",
	CONVERSATION_SENT_FROM_SERVER: "CONVERSATION",
	MESSAGE_SEEN: "MESSAGE_SEEN",
	ON_MESSAGE_SEEN: "ON_MESSAGE_SEEN",
	NEW_NOTIFICATION: "NEW_NOTIFICATION",
	DELETE_NOTIFICATION: "DELETE_NOTIFICATION",
};

export default SOCKET_CONST;
