const SOCKET_CONST = {
	MESSAGE_RECEIVED_FROM_CLIENT: "MESSAGE_SENT",
	MESSAGE_SENT_FROM_SERVER: "MESSAGE_RECEIVED",
	OFFLINE: "OFFLINE",
	CONVERSATION_SENT_FROM_SERVER: "CONVERSATION",
	MESSAGE_SEEN: "MESSAGE_SEEN",
	ON_MESSAGE_SEEN: "ON_MESSAGE_SEEN",
};

export default SOCKET_CONST;
